pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - check-success=Bot Says OK
    actions:
      merge:
        method: merge
        strict_method: rebase
        strict: true

